# Test Vagrantfile (reuse solution box)

Vagrant.configure("2") do |config|
  solution_box_path = ENV['ACTUAL_SOLUTION_BOX_PATH'] || "box/solution/solution.box"
  config.vm.box = solution_box_path

  # Sync project root to /vagrant so VM sees host updates immediately
  config.vm.synced_folder "../", "/vagrant"

  config.vm.network "private_network", type: "dhcp"

  common_cpus   = 8
  common_memory = 16384

  config.vm.provider :virtualbox do |vb|
    vb.name = "test-solution-virtualbox"
    vb.cpus = common_cpus
    vb.memory = common_memory
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.gui = false
  end

  config.vm.provider :libvirt do |lv|
    lv.driver = "kvm"
    require 'etc'
    dirname = __dir__.split('/')[-2..-1].join('-')
    lv.default_prefix = "#{Etc.getpwuid.uid}-#{dirname}-"
    lv.cpus   = common_cpus
    lv.memory = common_memory
  end

  # Ensure PATH for user installs
  config.vm.provision "shell", inline: <<-SHELL
    echo 'export PATH=$HOME/.local/bin:/usr/local/bin:$PATH' >> /home/vagrant/.profile
    export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
  SHELL
end


