# =============================================================================
# Options to control the build

# By default, running Vagrant will use the virtualbox provider. To use the
# libvirt provider with KVM, add PROVIDER=libvirt to the make invocation.

PROVIDER ?= virtualbox

# By default, tests are run to demonstrate that the flooding mechanisms is
# working. To disable the tests, add DISABLE_TEST=1 to the make invocation.

DISABLE_TEST ?=

# Example invocations:
#    make                                  -- build using virtualbox
#    make PROVIDER=libvirt DISABLE_TEST=1  -- build using KVM without tests
#    make PROVIDER=libvirt deep-clean      -- deep-clean using KVM

export PROVIDER
export DISABLE_TEST

# =============================================================================
# Master Control Makefile

BOXES = box/initial/initial.$(PROVIDER).box \
        box/baseline/baseline.$(PROVIDER).box \
        box/solution/solution.$(PROVIDER).box

# Temporarily export logs of all nodes.
MOBILITY_LOG_NODES ?= core agg1 agg2 acc1 acc2 acc3 acc4 acc5 acc6 producer consumer

# --- Main Experiment Outputs ---
# These variables define the key result files generated by the analysis scripts.

# Result roots
BASELINE_ROOT_DIR := results/baseline
SOLUTION_DIR := results/solution

# Baseline parameter-set configuration
BASELINE_PROFILE_CONFIG := experiment/tool/baseline_profiles.json
BASELINE_PROFILE_TOOL := experiment/tool/baseline_profiles.py
BASELINE_DEFAULT_DIR := $(shell python3 $(BASELINE_PROFILE_TOOL) --config $(BASELINE_PROFILE_CONFIG) print-default-dir --root-dir $(BASELINE_ROOT_DIR))
BASELINE_COLLECTION_STAMP := $(BASELINE_ROOT_DIR)/.complete

# (R1) Throughput
BASELINE_THROUGHPUT_PDF := $(BASELINE_DEFAULT_DIR)/throughput_timeseries.pdf
SOLUTION_THROUGHPUT_PDF := $(SOLUTION_DIR)/throughput_timeseries.pdf

# (R2) Service Disruption
BASELINE_DISRUPTION_PDF := $(BASELINE_DEFAULT_DIR)/disruption_times.pdf
SOLUTION_DISRUPTION_PDF := $(SOLUTION_DIR)/disruption_times.pdf

# (R3) Unmet-Interest Ratio
BASELINE_LOSS_PDF := $(BASELINE_DEFAULT_DIR)/loss_comparison.pdf
SOLUTION_LOSS_PDF := $(SOLUTION_DIR)/loss_comparison.pdf

# (R4) Flooding Overhead
BASELINE_OVERHEAD_TIMESERIES_PDF := $(BASELINE_DEFAULT_DIR)/overhead_timeseries.pdf
BASELINE_OVERHEAD_SUMMARY_PDF := $(BASELINE_DEFAULT_DIR)/overhead_summary.pdf
SOLUTION_OVERHEAD_TIMESERIES_PDF := $(SOLUTION_DIR)/overhead_timeseries.pdf
SOLUTION_OVERHEAD_SUMMARY_PDF := $(SOLUTION_DIR)/overhead_summary.pdf

# Baseline parameter-set comparison outputs
BASELINE_PROFILE_SUMMARY_CSV := $(BASELINE_ROOT_DIR)/summary.csv
BASELINE_PROFILE_DISRUPTION_PDF := $(BASELINE_ROOT_DIR)/disruption_comparison.pdf
BASELINE_PROFILE_COST_PDF := $(BASELINE_ROOT_DIR)/network_cost_comparison.pdf

# --- Paper Figure Dependencies ---
# These variables link the experiment outputs to the figures in the paper.
MAIN_TEX := paper/OptoFlood.tex
PAPER_BIN := paper/bin
LATEXMK := latexmk
LATEXMK_FLAGS := -pdf -interaction=nonstopmode -output-directory=$(PAPER_BIN)

# Define final figure paths for the paper
BASELINE_DISRUPTION_FIGURE := paper/figures/baseline_disruption.pdf
SOLUTION_DISRUPTION_FIGURE := paper/figures/solution_disruption.pdf
BASELINE_LOSS_FIGURE       := paper/figures/baseline_loss.pdf
SOLUTION_LOSS_FIGURE       := paper/figures/solution_loss.pdf
BASELINE_OVERHEAD_TIMESERIES_FIGURE := paper/figures/baseline_overhead_timeseries.pdf
BASELINE_OVERHEAD_SUMMARY_FIGURE    := paper/figures/baseline_overhead_summary.pdf
SOLUTION_OVERHEAD_TIMESERIES_FIGURE := paper/figures/solution_overhead_timeseries.pdf
SOLUTION_OVERHEAD_SUMMARY_FIGURE    := paper/figures/solution_overhead_summary.pdf
BASELINE_THROUGHPUT_FIGURE := paper/figures/baseline_throughput.pdf
SOLUTION_THROUGHPUT_FIGURE := paper/figures/solution_throughput.pdf

# Group all figures needed for the paper
BASELINE_PAPER_FIGURES := $(BASELINE_DISRUPTION_FIGURE) $(BASELINE_LOSS_FIGURE) \
                          $(BASELINE_OVERHEAD_TIMESERIES_FIGURE) $(BASELINE_OVERHEAD_SUMMARY_FIGURE) \
                          $(BASELINE_THROUGHPUT_FIGURE)
SOLUTION_PAPER_FIGURES := $(SOLUTION_DISRUPTION_FIGURE) $(SOLUTION_LOSS_FIGURE) \
                          $(SOLUTION_OVERHEAD_TIMESERIES_FIGURE) $(SOLUTION_OVERHEAD_SUMMARY_FIGURE) \
                          $(SOLUTION_THROUGHPUT_FIGURE)

PAPER_PDF := paper/OptoFlood.pdf
STATIC_FIGURES := paper/figures/NDN_Packets_Processing_Flow.pdf \
                  paper/figures/NDN_Producer_Mobility_Problem.pdf \
                  paper/figures/NDN_Producer_Mobility_Problem_Solution.pdf \
                  paper/figures/Topology.pdf
ALL_FIGURES := $(STATIC_FIGURES) $(BASELINE_PAPER_FIGURES) $(SOLUTION_PAPER_FIGURES)

# Common application source files
APP_SRCS := experiment/app/producer.cpp \
            experiment/app/consumer.cpp \
            experiment/app/trust-schema.conf

# Experiment-specific source files
BASELINE_SRCS := experiment/baseline/Vagrantfile \
                experiment/baseline/Makefile
                
SOLUTION_SRCS := experiment/solution/Vagrantfile \
                experiment/solution/Makefile

# Tooling split by pipeline:
# - EXPERIMENT_TOOL_SRCS: affects VM experiment run and CSV generation
# - PLOT_TOOL_SRCS: affects host-side figure regeneration only
# - TEST_TOOL_SRCS: affects validation/test flow only
# - PLOT_ENV_SRCS: affects host plotting Python environment
EXPERIMENT_TOOL_SRCS := experiment/tool/exp.py \
                        experiment/tool/extract_overhead_csv.py
PLOT_LATENCY_SCRIPT := experiment/tool/plot_latency.py
PLOT_LOSS_SCRIPT := experiment/tool/plot_loss.py
PLOT_OVERHEAD_SCRIPT := experiment/tool/plot_overhead.py
PLOT_OVERHEAD_YMAX_SCRIPT := experiment/tool/compute_overhead_ymax.py
PLOT_THROUGHPUT_SCRIPT := experiment/tool/plot_throughput.py
BASELINE_PROFILE_SUMMARY_SCRIPT := experiment/tool/summarize_nlsr_sensitivity.py
BASELINE_PROFILE_DISRUPTION_SCRIPT := experiment/tool/plot_nlsr_disruption_comparison.py
BASELINE_PROFILE_COST_SCRIPT := experiment/tool/plot_nlsr_network_cost_comparison.py
PLOT_RESULT_METRICS_SCRIPT := experiment/tool/plot_result_metrics.py
PLOT_BASELINE_PROFILES_SCRIPT := experiment/tool/plot_baseline_profiles.py
PLOT_MAIN_RESULTS_SCRIPT := experiment/tool/plot_main_results.py
RUN_BASELINE_PROFILES_SCRIPT := scripts/run-baseline-profiles.py
RUN_RESULT_COLLECTION_SCRIPT := scripts/run-result-collection.sh
VALIDATE_RESULT_DIR_SCRIPT := scripts/validate_result_dir.py
PLOT_TOOL_SRCS := $(PLOT_LATENCY_SCRIPT) \
                  $(PLOT_LOSS_SCRIPT) \
                  $(PLOT_OVERHEAD_SCRIPT) \
                  $(PLOT_OVERHEAD_YMAX_SCRIPT) \
                  $(PLOT_THROUGHPUT_SCRIPT) \
                  $(BASELINE_PROFILE_SUMMARY_SCRIPT) \
                  $(BASELINE_PROFILE_DISRUPTION_SCRIPT) \
                  $(BASELINE_PROFILE_COST_SCRIPT) \
                  $(BASELINE_PROFILE_TOOL) \
                  $(PLOT_RESULT_METRICS_SCRIPT) \
                  $(PLOT_BASELINE_PROFILES_SCRIPT) \
                  $(PLOT_MAIN_RESULTS_SCRIPT)
PIPELINE_TOOL_SRCS := $(VALIDATE_RESULT_DIR_SCRIPT) \
                      $(RUN_BASELINE_PROFILES_SCRIPT) \
                      $(BASELINE_PROFILE_TOOL) \
                      $(BASELINE_PROFILE_CONFIG)
TEST_TOOL_SRCS := experiment/tool/ndn.lua
PLOT_ENV_SRCS := experiment/tool/requirements.txt

# Host-side plotting environment (for re-generating figures without re-running experiments)
VENV_DIR := experiment/tool/.venv
PYTHON   := $(VENV_DIR)/bin/python3

CSV_BASELINE_DEFAULT := $(BASELINE_DEFAULT_DIR)/consumer_capture.csv
CSV_SOLUTION := $(SOLUTION_DIR)/consumer_capture.csv
OVERHEAD_CSV_BASELINE_DEFAULT := $(BASELINE_DEFAULT_DIR)/network_overhead.csv
OVERHEAD_CSV_SOLUTION := $(SOLUTION_DIR)/network_overhead.csv
TEST_VALIDATE_OK := test/.validate_ok
TEST_SRCS := test/Makefile test/Vagrantfile test/exp_test.py test/validate.py \
             experiment/app/producer.cpp experiment/app/consumer.cpp \
             experiment/app/trust-schema.conf $(TEST_TOOL_SRCS)

# SSH config files used by host-side rsync/ssh invocations.
BASELINE_SSH_CONFIG := .ssh_config_baseline
SOLUTION_SSH_CONFIG := .ssh_config_solution

# Vagrant command wrappers for experiment VMs.
VAGRANT_BASELINE = VAGRANT_DEFAULT_PROVIDER=$(PROVIDER) VAGRANT_CWD=experiment/baseline vagrant
VAGRANT_SOLUTION = VAGRANT_DEFAULT_PROVIDER=$(PROVIDER) VAGRANT_CWD=experiment/solution vagrant

# Refresh cached SSH endpoints after `vagrant up`, because providers may
# reassign guest addresses or forwarded ports between runs.
REFRESH_BASELINE_SSH_CONFIG = $(VAGRANT_BASELINE) ssh-config --host baseline > $(BASELINE_SSH_CONFIG)
REFRESH_SOLUTION_SSH_CONFIG = $(VAGRANT_SOLUTION) ssh-config --host solution > $(SOLUTION_SSH_CONFIG)

# Run one result-collection workflow from the repository root.
RUN_RESULT_COLLECTION = PROVIDER=$(PROVIDER) MOBILITY_LOG_NODES="$(MOBILITY_LOG_NODES)" sh $(RUN_RESULT_COLLECTION_SCRIPT)

# Run repository cleanup workflows from the repository root.
RUN_CLEANUP = PROVIDER=$(PROVIDER) LATEXMK=$(LATEXMK) sh scripts/cleanup.sh

# Main target (set DISABLE_TEST=1 to skip tests)
all: $(BOXES) experiment $(if $(DISABLE_TEST),,$(TEST_VALIDATE_OK)) result paper

# High-level orchestration targets (set the provider via `PROVIDER=...` when needed)
.PHONY: boxes experiment experiment-baseline experiment-solution experiment-nlsr-tuning \
        result plot plot-baseline plot-main plot-nlsr-tuning paper test mypy vm-clean


# Experiments (run inside VMs and pull back CSVs)
experiment-baseline: $(BASELINE_COLLECTION_STAMP)

experiment-solution: $(CSV_SOLUTION) $(OVERHEAD_CSV_SOLUTION)

# Backward-compatible alias for the baseline parameter-set experiment pipeline.
experiment-nlsr-tuning: experiment-baseline plot-baseline

# Run both experiments
experiment: experiment-baseline experiment-solution

# Assemble result figures for the paper (copy from results/ to paper/figures)
result: $(BASELINE_PAPER_FIGURES) $(SOLUTION_PAPER_FIGURES)

# Run the test experiment
test: $(TEST_VALIDATE_OK)

$(TEST_VALIDATE_OK): $(TEST_SRCS) box/solution/solution.$(PROVIDER).box
	$(MAKE) -C test PROVIDER=$(PROVIDER) test-all

# Plot only (reuse existing CSVs; no VM run)
plot: plot-baseline plot-main

plot-baseline: | $(VENV_DIR)
	$(PYTHON) $(PLOT_BASELINE_PROFILES_SCRIPT) --root-dir $(BASELINE_ROOT_DIR) --profile-config $(BASELINE_PROFILE_CONFIG) --plot-driver $(PLOT_RESULT_METRICS_SCRIPT) --summary-script $(BASELINE_PROFILE_SUMMARY_SCRIPT) --disruption-comparison-script $(BASELINE_PROFILE_DISRUPTION_SCRIPT) --cost-comparison-script $(BASELINE_PROFILE_COST_SCRIPT) --latency-script $(PLOT_LATENCY_SCRIPT) --overhead-script $(PLOT_OVERHEAD_SCRIPT) --handoff-times "120, 240"

plot-main: | $(VENV_DIR)
	$(PYTHON) $(VALIDATE_RESULT_DIR_SCRIPT) --result-dir "$(BASELINE_DEFAULT_DIR)" --require-params
	$(PYTHON) $(VALIDATE_RESULT_DIR_SCRIPT) --result-dir "$(SOLUTION_DIR)"
	$(PYTHON) $(PLOT_MAIN_RESULTS_SCRIPT) --baseline-dir "$(BASELINE_DEFAULT_DIR)" --solution-dir "$(SOLUTION_DIR)" --plot-driver $(PLOT_RESULT_METRICS_SCRIPT) --overhead-ymax-script $(PLOT_OVERHEAD_YMAX_SCRIPT) --latency-script $(PLOT_LATENCY_SCRIPT) --loss-script $(PLOT_LOSS_SCRIPT) --throughput-script $(PLOT_THROUGHPUT_SCRIPT) --overhead-script $(PLOT_OVERHEAD_SCRIPT) --handoff-times "120, 240"

# Backward-compatible alias for the baseline parameter-set plot pipeline.
plot-nlsr-tuning: plot-baseline

# Build the paper PDF (follow dependencies; do not hand-check and exit)
paper: $(PAPER_PDF)

# Ensure results directories exist
results:
	mkdir $@

results/baseline: | results
	mkdir $@

results/solution: | results
	mkdir $@

paper/figures:
	mkdir $@

# Type checking (mypy) using host venv
mypy: | $(VENV_DIR)
	$(PYTHON) -m mypy --config-file mypy.ini test/validate.py $(PLOT_TOOL_SRCS) $(filter %.py,$(PIPELINE_TOOL_SRCS))


# =============================================================================
# Rules to build the Vagrant boxes

build-boxes: boxes

box: boxes

box-initial: box/initial/initial.$(PROVIDER).box

box-baseline: box/baseline/baseline.$(PROVIDER).box

box-solution: box/solution/solution.$(PROVIDER).box

boxes: $(BOXES)

box/initial/initial.$(PROVIDER).box: box/initial/Vagrantfile
	PROVIDER=$(PROVIDER) sh scripts/make-box.sh $(dir $<) $@

box/baseline/baseline.$(PROVIDER).box: box/baseline/Vagrantfile box/initial/initial.$(PROVIDER).box
	PROVIDER=$(PROVIDER) sh scripts/make-box.sh $(dir $<) $@

box/solution/solution.$(PROVIDER).box: box/solution/Vagrantfile box/initial/initial.$(PROVIDER).box
	PROVIDER=$(PROVIDER) sh scripts/make-box.sh $(dir $<) $@


# =============================================================================


# SSH config file for baseline experiment
$(BASELINE_SSH_CONFIG): experiment/baseline/Vagrantfile box/baseline/baseline.$(PROVIDER).box
	# Force destroy any lingering VM to ensure a clean state
	$(VAGRANT_BASELINE) destroy -f || true
	ACTUAL_BASELINE_BOX_PATH="box/baseline/baseline.$(PROVIDER).box" \
	$(VAGRANT_BASELINE) up --provision
	$(REFRESH_BASELINE_SSH_CONFIG)

# SSH config file for solution experiment
$(SOLUTION_SSH_CONFIG): experiment/solution/Vagrantfile box/solution/solution.$(PROVIDER).box
	# Force destroy any lingering VM to ensure a clean state
	$(VAGRANT_SOLUTION) destroy -f || true
	ACTUAL_SOLUTION_BOX_PATH="box/solution/solution.$(PROVIDER).box" \
	$(VAGRANT_SOLUTION) up --provision
	$(REFRESH_SOLUTION_SSH_CONFIG)

# Remote working directory inside VMs (standardized for rsync-based runs)
REMOTE_DIR := /home/vagrant/flooding


# Baseline parameter-set collection
$(BASELINE_COLLECTION_STAMP): $(APP_SRCS) $(BASELINE_SRCS) $(EXPERIMENT_TOOL_SRCS) $(PIPELINE_TOOL_SRCS) $(RUN_RESULT_COLLECTION_SCRIPT) $(VALIDATE_RESULT_DIR_SCRIPT) $(BASELINE_SSH_CONFIG) | results/baseline
	PROVIDER=$(PROVIDER) MOBILITY_LOG_NODES="$(MOBILITY_LOG_NODES)" python3 $(RUN_BASELINE_PROFILES_SCRIPT) --config $(BASELINE_PROFILE_CONFIG) --results-root $(BASELINE_ROOT_DIR) --vagrant-dir experiment/baseline --host-alias baseline --ssh-config $(BASELINE_SSH_CONFIG) --box-env-name ACTUAL_BASELINE_BOX_PATH --box-path box/baseline/baseline.$(PROVIDER).box --source-dir ./ --remote-dir $(REMOTE_DIR) --experiment-subdir experiment/baseline --run-script $(RUN_RESULT_COLLECTION_SCRIPT)
	@echo OK > $@

$(CSV_BASELINE_DEFAULT) $(OVERHEAD_CSV_BASELINE_DEFAULT) $(BASELINE_DEFAULT_DIR)/params.txt &: $(BASELINE_COLLECTION_STAMP)
	@test -f "$@"

# Solution: build CSV via one VM run, then host will plot PDFs from CSV
$(CSV_SOLUTION) $(OVERHEAD_CSV_SOLUTION) &: $(APP_SRCS) $(SOLUTION_SRCS) $(EXPERIMENT_TOOL_SRCS) $(RUN_RESULT_COLLECTION_SCRIPT) $(VALIDATE_RESULT_DIR_SCRIPT) $(SOLUTION_SSH_CONFIG) | results/solution
	$(RUN_RESULT_COLLECTION) experiment/solution solution $(SOLUTION_SSH_CONFIG) ACTUAL_SOLUTION_BOX_PATH box/solution/solution.$(PROVIDER).box ./ $(REMOTE_DIR) experiment/solution $(SOLUTION_DIR)

# Host-side venv for plotting
$(VENV_DIR): $(PLOT_ENV_SRCS)
	python3 -m venv $(VENV_DIR)
	$(VENV_DIR)/bin/pip install -r $(PLOT_ENV_SRCS)
	touch $(VENV_DIR)

# Plot baseline(default) and solution full metric sets with shared overhead axes
$(BASELINE_DISRUPTION_PDF) $(BASELINE_DEFAULT_DIR)/disruption_metrics.txt \
$(BASELINE_LOSS_PDF) $(BASELINE_DEFAULT_DIR)/loss_ratio.txt \
$(BASELINE_THROUGHPUT_PDF) $(BASELINE_DEFAULT_DIR)/throughput_metrics.txt \
$(BASELINE_OVERHEAD_TIMESERIES_PDF) $(BASELINE_OVERHEAD_SUMMARY_PDF) $(BASELINE_DEFAULT_DIR)/overhead_total.txt \
$(SOLUTION_DISRUPTION_PDF) $(SOLUTION_DIR)/disruption_metrics.txt \
$(SOLUTION_LOSS_PDF) $(SOLUTION_DIR)/loss_ratio.txt \
$(SOLUTION_THROUGHPUT_PDF) $(SOLUTION_DIR)/throughput_metrics.txt \
$(SOLUTION_OVERHEAD_TIMESERIES_PDF) $(SOLUTION_OVERHEAD_SUMMARY_PDF) $(SOLUTION_DIR)/overhead_total.txt &: \
	$(CSV_BASELINE_DEFAULT) $(OVERHEAD_CSV_BASELINE_DEFAULT) $(CSV_SOLUTION) $(OVERHEAD_CSV_SOLUTION) \
	$(PIPELINE_TOOL_SRCS) $(PLOT_RESULT_METRICS_SCRIPT) $(PLOT_MAIN_RESULTS_SCRIPT) $(PLOT_LATENCY_SCRIPT) $(PLOT_LOSS_SCRIPT) $(PLOT_THROUGHPUT_SCRIPT) \
	$(PLOT_OVERHEAD_SCRIPT) $(PLOT_OVERHEAD_YMAX_SCRIPT) | $(VENV_DIR) $(SOLUTION_DIR)
	$(PYTHON) $(PLOT_MAIN_RESULTS_SCRIPT) --baseline-dir "$(BASELINE_DEFAULT_DIR)" --solution-dir "$(SOLUTION_DIR)" --plot-driver $(PLOT_RESULT_METRICS_SCRIPT) --overhead-ymax-script $(PLOT_OVERHEAD_YMAX_SCRIPT) --latency-script $(PLOT_LATENCY_SCRIPT) --loss-script $(PLOT_LOSS_SCRIPT) --throughput-script $(PLOT_THROUGHPUT_SCRIPT) --overhead-script $(PLOT_OVERHEAD_SCRIPT) --handoff-times "120, 240"

# --- Copy Results to Paper Directory ---

$(BASELINE_DISRUPTION_FIGURE): $(BASELINE_DISRUPTION_PDF) | paper/figures
	cp "$(BASELINE_DISRUPTION_PDF)" "$@"

$(BASELINE_LOSS_FIGURE): $(BASELINE_LOSS_PDF) | paper/figures
	cp "$(BASELINE_LOSS_PDF)" "$@"

$(BASELINE_OVERHEAD_TIMESERIES_FIGURE): $(BASELINE_OVERHEAD_TIMESERIES_PDF) | paper/figures
	cp "$(BASELINE_OVERHEAD_TIMESERIES_PDF)" "$@"

$(BASELINE_OVERHEAD_SUMMARY_FIGURE): $(BASELINE_OVERHEAD_SUMMARY_PDF) | paper/figures
	cp "$(BASELINE_OVERHEAD_SUMMARY_PDF)" "$@"

$(BASELINE_THROUGHPUT_FIGURE): $(BASELINE_THROUGHPUT_PDF) | paper/figures
	cp "$(BASELINE_THROUGHPUT_PDF)" "$@"

$(SOLUTION_DISRUPTION_FIGURE): $(SOLUTION_DISRUPTION_PDF) | paper/figures
	cp "$(SOLUTION_DISRUPTION_PDF)" "$@"

$(SOLUTION_LOSS_FIGURE): $(SOLUTION_LOSS_PDF) | paper/figures
	cp "$(SOLUTION_LOSS_PDF)" "$@"

$(SOLUTION_OVERHEAD_TIMESERIES_FIGURE): $(SOLUTION_OVERHEAD_TIMESERIES_PDF) | paper/figures
	cp "$(SOLUTION_OVERHEAD_TIMESERIES_PDF)" "$@"

$(SOLUTION_OVERHEAD_SUMMARY_FIGURE): $(SOLUTION_OVERHEAD_SUMMARY_PDF) | paper/figures
	cp "$(SOLUTION_OVERHEAD_SUMMARY_PDF)" "$@"

$(SOLUTION_THROUGHPUT_FIGURE): $(SOLUTION_THROUGHPUT_PDF) | paper/figures
	cp "$(SOLUTION_THROUGHPUT_PDF)" "$@"

# Generate the paper
$(PAPER_PDF): $(MAIN_TEX) $(ALL_FIGURES) | $(PAPER_BIN)
	@echo "Compiling LaTeX with latexmk..."
	$(LATEXMK) $(LATEXMK_FLAGS) $(MAIN_TEX)
	cp $(PAPER_BIN)/$(notdir $(PAPER_PDF)) $(PAPER_PDF)

$(PAPER_BIN):
	mkdir -p $(PAPER_BIN)


# Cleanup
clean:
	$(RUN_CLEANUP) clean

deep-clean: clean
	$(RUN_CLEANUP) deep-clean

# Clean SSH config file
clean-ssh-config:
	rm -f $(BASELINE_SSH_CONFIG) $(SOLUTION_SSH_CONFIG)

# Destroy all VMs (keep boxes)
vm-clean:
	$(RUN_CLEANUP) vm-clean


.PHONY: all build-boxes boxes clean deep-clean clean-ssh-config box box-initial box-baseline box-solution experiment experiment-baseline experiment-solution experiment-nlsr-tuning result plot plot-baseline plot-main plot-nlsr-tuning paper test mypy vm-clean

.DELETE_ON_ERROR:

.NOTINTERMEDIATE:
