# Solution Box Vagrantfile

$INSTALL_BASE = <<EOF
  set -e -u -o pipefail

  # Clone and install mini-ndn
  git clone https://github.com/named-data/mini-ndn.git /home/vagrant/mini-ndn
  cd /home/vagrant/mini-ndn
  git checkout 73add71f860979426aef63136bf78ed525862e5c
  ./install.sh -y \
  --cxx=https://github.com/TheBigRedOne/ndn-cxx.git@cd9ea187f1e377c5ee5c2cd644ed1b696a50257b \
  --nfd=https://github.com/TheBigRedOne/NFD.git@4b98b97386562ad3acaabc94397f2d33c0e752ac \
  --psync=https://github.com/TheBigRedOne/PSync.git@e0ef02c3dce38f138152d4b86a426c113a9f5e53 \
  --nlsr=https://github.com/TheBigRedOne/NLSR.git@0f9430af1dde2ac0117d627b2d51b070fde7b976 \
  --tools=https://github.com/named-data/ndn-tools.git@ndn-tools-24.07 \
  --traffic=https://github.com/named-data/ndn-traffic-generator.git@9bec15ac63ae2ac225c4e514daa9fc1366889d62 \
  --infoedit=https://github.com/NDN-Routing/infoedit.git@cecfe583f5d2df974f5cbd50996f91b9d321be99 \
  --no-wifi \
  --jobs=8

  # --- Install NDN Wireshark Dissector ---
  # Create a standard directory for the dissector
  sudo mkdir -p /usr/local/share/ndn-dissect-wireshark
  # Copy the dissector from the synced folder to the standard location
  sudo cp /home/vagrant/mini-ndn/dl/ndn-tools/tools/dissect-wireshark/ndn.lua /usr/local/share/ndn-dissect-wireshark/
  # Find the global wireshark init.lua and append the dofile command to load our dissector
  INIT_LUA_PATH=$(find /usr/share/wireshark -name "init.lua" | head -n 1)
  if [ -f "$INIT_LUA_PATH" ]; then
    echo 'dofile("/usr/local/share/ndn-dissect-wireshark/ndn.lua")' | sudo tee -a $INIT_LUA_PATH
  else
    echo "Wireshark init.lua not found, dissector not installed."
  fi
  # --- End Dissector Install ---

  # Set environment variables in .profile
  echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib64/" >> /home/vagrant/.profile
  echo "export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/" >> /home/vagrant/.profile
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "box/initial/initial." + ENV["PROVIDER"] + ".box"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # The --jobs= parameter to ./install.sh (above) should match common_cpus
  common_cpus   = 8
  common_memory = 16384

  config.vm.provider :virtualbox do |vb|
    vb.name = "solution-virtualbox"
    vb.cpus = common_cpus
    vb.memory = common_memory
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.gui = false
  end

  config.vm.provider :libvirt do |lv|
    lv.driver = "kvm"
    require 'etc'
    dirname = __dir__.split('/')[-2..-1].join('-')
    lv.default_prefix = "#{Etc.getpwuid.uid}-#{dirname}-"
    lv.cpus   = common_cpus
    lv.memory = common_memory
  end

  config.vm.provision "shell", inline: $INSTALL_BASE, privileged: false

end
