# Solution Box Vagrantfile

$INSTALL_BASE = <<EOF
  export DEBIAN_FRONTEND=noninteractive

  # Clone and install mini-ndn
  git clone https://github.com/TheBigRedOne/mini-ndn.git /home/vagrant/mini-ndn
  cd /home/vagrant/mini-ndn
  git checkout 727e028c6d2fa04ddf6553aabb68a29cd123c221
  ./install.sh -y
  --cxx=https://github.com/TheBigRedOne/ndn-cxx.git@e5b9c70e8f65908a4146aa09318770bba1804063 \
  --nfd=https://github.com/TheBigRedOne/NFD.git@51a4a64228ed644442463c98ac32ed7c48d2ed85 \
  --psync=https://github.com/named-data/PSync.git@0.5.0 \
  --nlsr=https://github.com/named-data/NLSR.git@NLSR-24.08 \
  --tools=https://github.com/named-data/ndn-tools.git@ndn-tools-24.07 \
  --traffic=https://github.com/named-data/ndn-traffic-generator.git@9bec15ac63ae2ac225c4e514daa9fc1366889d62 \
  --infoedit=https://github.com/NDN-Routing/infoedit.git@cecfe583f5d2df974f5cbd50996f91b9d321be99

  # Set environment variables in .profile
  echo "export PATH=\$PATH:/usr/local/bin" >> /home/vagrant/.profile
  echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib64/" >> /home/vagrant/.profile
  echo "export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/" >> /home/vagrant/.profile
EOF

Vagrant.configure("2") do |config|
  initial_box_path = ENV['ACTUAL_INITIAL_BOX_PATH'] || "box/initial/initial.box"
  config.vm.box = initial_box_path

  config.vm.network "private_network", type: "dhcp"
  
  common_cpus   = 4
  common_memory = 4096

  config.vm.provider :virtualbox do |vb|
    vb.name = "solution-virtualbox"
    vb.cpus = common_cpus
    vb.memory = common_memory
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.gui = false
  end

  config.vm.provider :libvirt do |lv|
    lv.driver = "kvm"
    require 'etc'
    dirname = __dir__.split('/')[-2..-1].join('-')
    lv.default_prefix = "#{Etc.getpwuid.uid}-#{dirname}-"
    lv.cpus   = common_cpus
    lv.memory = common_memory
  end

  config.vm.provision "shell", inline: $INSTALL_BASE, privileged: false

end
