# Baseline Box Vagrantfile

$INSTALL_BASE = <<EOF
  export DEBIAN_FRONTEND=noninteractive

  # Clone mini-ndn release v0.7.0 and install release 2024-08
  git clone https://github.com/named-data/mini-ndn.git /home/vagrant/mini-ndn
  cd /home/vagrant/mini-ndn
  git checkout 73add71f860979426aef63136bf78ed525862e5c
  ./install.sh -y --release=2024-08

  # Set environment variables in .profile
  echo "export PATH=\$PATH:/usr/local/bin" >> /home/vagrant/.profile
  echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib64/" >> /home/vagrant/.profile
  echo "export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/" >> /home/vagrant/.profile
EOF

Vagrant.configure("2") do |config|
  initial_box_path = ENV['ACTUAL_INITIAL_BOX_PATH'] || "boxes/initial/initial.box"
  config.vm.box = initial_box_path
  
  config.vm.network "private_network", type: "dhcp"

  common_cpus   = 4
  common_memory = 4096

  config.vm.provider :virtualbox do |vb|
    vb.name = "baseline-virtualbox"
    vb.cpus = common_cpus
    vb.memory = common_memory
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.gui = false
  end

  config.vm.provider :libvirt do |lv|
    lv.driver = "kvm"
    lv.cpus   = common_cpus
    lv.memory = common_memory
  end

  config.vm.provision "shell", inline: $INSTALL_BASE, privileged: false

end
