name: Docker
on:
  push:
    tags:
      - 'ndn-tools-[0-9]+*'
  schedule:
    # twice a month
    - cron: '20 10 5,20 * *'
  workflow_dispatch:

permissions:
  attestations: write
  id-token: write
  packages: write

jobs:
  ndn-tools:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndn-tools
