name: Release
on:
  push:
    tags:
      - 'ndn-tools-[0-9]+*'
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    uses: named-data/actions/.github/workflows/release.yml@v1
