$INSTALL_BASE = <<EOF
  export DEBIAN_FRONTEND=noninteractive

  sudo apt-get update
  sudo apt-get install -y build-essential python3-pip python3-pep8 pkg-config \
                          libboost-all-dev libssl-dev libsqlite3-dev libpcap-dev \
                          libsystemd-dev tcpdump

  # Clone and install mini-ndn
  git clone https://github.com/named-data/mini-ndn.git /home/vagrant/mini-ndn
  cd /home/vagrant/mini-ndn
  git checkout b5c893d5a190f530885a4e31ce440e7077848f97
  ./install.sh -y --source

  # Change ownership of mini-ndn folder to vagrant user
  sudo chown -R vagrant:vagrant /home/vagrant/mini-ndn

  # Set environment variables (for non-interactive shells)
  echo "export PATH=\$PATH:/usr/local/bin" >> /home/vagrant/.profile
  echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib64/" >> /home/vagrant/.profile
  echo "export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/" >> /home/vagrant/.profile
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202407.23.0"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--cpus", "4"]
    v.customize ["modifyvm", :id, "--memory", "32768"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.gui = false
  end

  config.vm.provision "shell", inline: $INSTALL_BASE, privileged: false
end
