#Initial Box Vagrantfile

$INSTALL_BASE = <<EOF
  export DEBIAN_FRONTEND=noninteractive

  # Update and install dependencies
  sudo apt-get update
  sudo apt-get install -y build-essential 
  sudo apt-get install -y python3-pip 
  sudo apt-get install -y python3-pep8 
  sudo apt-get install -y pkg-config 
  sudo apt-get install -y libboost-all-dev 
  sudo apt-get install -y libssl-dev 
  sudo apt-get install -y libsqlite3-dev 
  sudo apt-get install -y libpcap-dev 
  sudo apt-get install -y libsystemd-dev
  sudo apt-get install -y tcpdump

  # Set environment variables in .profile rather than .bashrc
  echo "export PATH=\$PATH:/usr/local/bin" >> /home/vagrant/.profile
  echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib64/" >> /home/vagrant/.profile
  echo "export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/" >> /home/vagrant/.profile
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202407.23.0"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider :virtualbox do |v|
    #v.customize ["modifyvm", :id, "--cpus", "18"]
    #v.customize ["modifyvm", :id, "--memory", "32768"]
    v.customize ["modifyvm", :id, "--cpus", "4"]
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.gui = false
  end

  config.vm.provision "shell", inline: $INSTALL_BASE, privileged: false
end
