name: CI
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.conf.sample*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'docs/**'
      - '.editorconfig'
      - '.gitignore'
      - '.mailmap'
      - '*.md'
  workflow_dispatch:

permissions: {}

jobs:
  Ubuntu:
    uses: named-data/actions/.github/workflows/jenkins-script-ubuntu.yml@v1
    with:
      submodules: true
  macOS:
    uses: named-data/actions/.github/workflows/jenkins-script-macos.yml@v1
    with:
      submodules: true
