# Baseline Vagrantfile

$INSTALL_BASE = <<EOF
  export DEBIAN_FRONTEND=noninteractive

  # Clone and install mini-ndn
  git clone https://github.com/named-data/mini-ndn.git /home/vagrant/mini-ndn
  cd /home/vagrant/mini-ndn
  git checkout b95d194f75d2d32956737602f741c9a54ff7906d
  ./install.sh -y --source 

  # Set environment variables in .profile rather than .bashrc
  echo "export PATH=\$PATH:/usr/local/bin" >> /home/vagrant/.profile
  echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib64/" >> /home/vagrant/.profile
  echo "export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/" >> /home/vagrant/.profile
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "initial"
  config.vm.box_url = "../../boxes/initial/initial.box"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--cpus", "4"]
    v.customize ["modifyvm", :id, "--memory", "32768"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.gui = false
  end

  config.vm.provision "shell", inline: $INSTALL_BASE, privileged: false

end
